# Generated by Django 4.0.6 on 2022-07-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
