# Generated by Django 4.0.6 on 2022-07-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_candidate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(blank=True, to='blog.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(blank=True, to='blog.skill'),
        ),
    ]
